name: Run tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run-script eslint
      - name: Run tests
        run: npm test
